# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(411, 550)
        MainWindow.setMinimumSize(QtCore.QSize(411, 0))
        MainWindow.setBaseSize(QtCore.QSize(260, 300))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../../opt/yin-yang/src/ui/assets/yin-yang.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.back_button = QtWidgets.QPushButton(self.centralWidget)
        self.back_button.setObjectName("back_button")
        self.horizontalLayout_2.addWidget(self.back_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.plugins = QtWidgets.QScrollArea(self.centralWidget)
        self.plugins.setWidgetResizable(True)
        self.plugins.setObjectName("plugins")
        self.plugins_scroll_content = QtWidgets.QWidget()
        self.plugins_scroll_content.setGeometry(QtCore.QRect(0, 0, 393, 430))
        self.plugins_scroll_content.setObjectName("plugins_scroll_content")
        self.plugins_scroll_content_layout = QtWidgets.QVBoxLayout(self.plugins_scroll_content)
        self.plugins_scroll_content_layout.setContentsMargins(11, 11, 11, 11)
        self.plugins_scroll_content_layout.setSpacing(6)
        self.plugins_scroll_content_layout.setObjectName("plugins_scroll_content_layout")
        self.plugins.setWidget(self.plugins_scroll_content)
        self.verticalLayout.addWidget(self.plugins)
        self.version_label = QtWidgets.QLabel(self.centralWidget)
        self.version_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.version_label.setObjectName("version_label")
        self.verticalLayout.addWidget(self.version_label)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Yin & Yang"))
        self.back_button.setText(_translate("MainWindow", "back"))
        self.label.setText(_translate("MainWindow", "Settings"))
        self.version_label.setText(_translate("MainWindow", "version: 0.1"))
